### ISSUE TITLE
Exception: while creating work item in TFS

### ISSUE THREAD

**Issue by abhaykPere** [Microsoft/vsts-dotnet-samples#153] opened 2018-07-23 11:50 UTC
Trying CreateWorkItemAsync() I am already passing AreaPath and IterationPath in patchDocument while creating workItem

Following is code:

patchDocument.Add(new JsonPatchOperation
{
                Operation = Microsoft.VisualStudio.Services.WebApi.Patch.Operation.Add,
                Path = "/Fields/System.AreaPath",
                Value = "test"
});

patchDocument.Add(new JsonPatchOperation
{
                Operation = Microsoft.VisualStudio.Services.WebApi.Patch.Operation.Add,
                Path = "/Fields/System.IterationPath",
                Value = "test"
});

WorkItem result = workItemTrackingHttpClient.CreateWorkItemAsync(patchDocument, teamProjectReference.Name, "Task").Result;

But I am facing exception as : New work item updates must specify Area and Iteration node ids. Parameter name: workItemUpdates

**Comment by danhellem** [comment] 2018-08-21 14:39
This is most likely caused by bad formatting of the value. Here is an example of assigning it to a iteration

patchDocument.Add(
               new JsonPatchOperation()
               {
                   Operation = Operation.Add,
                   Path = "/fields/System.IterationPath",
                   Value = "Test Project\\Iteration 1"
               }
           );

You should not need id's as long as the format is correct.

**Closed by danhellem** 2018-08-21 14:39 UTC
